add languageCode type
grammyjs/types pull request #45
Opened 2024-05-25 03:35 UTC by carafelix

Would be helpful for getting autocompletion in the commands plugin while localizing commands, could potentially improve readability in other places of the codebase.

```ts
userCommands.command("papin", "papon", async (c) => {
  await c.reply("papito");
}).localize('AUTOCOMPLETES HERE')
```

2024-05-25 09:19 UTC, roj1512 commented on langs.ts
Some languages have only 3-letter ISO codes.

2024-05-25 09:57 UTC, KnorpelSenf commented on langs.ts
They are not supported anyway. 
> A two-letter ISO 639-1 language code. If empty, commands will be applied to all users from the given scope, for whose language there are no dedicated commands

2024-05-25 21:04 UTC, roj1512 commented on langs.ts
Telegram translations support them tho. I should give it a try anyway.

2024-05-25 21:05 UTC, roj1512 commented on langs.ts
Yeah, they are not supported.

2024-05-25 23:01 UTC, carafelix commented on langs.ts
So we are good to go?

2024-05-26 17:56 UTC, carafelix commented
Should I declared this just locally for the commands plugin or better intended here?

2024-05-27 13:17 UTC, KnorpelSenf commented on langs.ts
Yes

2024-05-27 14:23 UTC, KnorpelSenf requested changes
I like
- that we are able to narrow down the types this way, it is specified well enough that we can do this
- that you added the types to this repo

I do not like that you used a TS enum, they are basically not much more than a footgun and since we do not expose any of its functionality, we might as well directly go with
```ts
export type LanguageCode =
  | "ab" // Abkhazian
  | "aa" // Afar
  // ...
```
Could you change this?

2024-05-27 14:39 UTC, roziscoding commented
> I do not like that you used a TS enum, they are basically not much more than a footgun and since we do not expose any of its functionality, we might as well directly go with
> 
> ```ts
> export type LanguageCode =
>   | "ab" // Abkhazian
>   | "aa" // Afar
>   // ...
> ```

I like the idea of not going with an enum, but I think having these at runtime would be useful so users don't need to look for the correct code for the language they're using, so I'd suggest we go with

```ts
export const LanguageCodes = {
  "ab": "Abkhazian",
  // ...
}

export type LanguageCode = keyof typeof LanguageCodes
```

2024-05-27 14:42 UTC, roziscoding commented
> I do not like that you used a TS enum, they are basically not much more than a footgun and since we do not expose any of its functionality, we might as well directly go with
> 
> ```ts
> export type LanguageCode =
>   | "ab" // Abkhazian
>   | "aa" // Afar
>   // ...
> ```

I like the idea of not going with an enum, but I think having these at runtime would be useful so users don't need to look for the correct code for the language they're using, so I'd suggest we go with

```ts
const LanguageCodes = {
  "Abkhazian": "ab",
  "Afar": "aa",
  // ...
} as const;

export type LanguageCode = typeof LanguageCodes[keyof typeof LanguageCodes];
```

2024-05-27 20:05 UTC, carafelix commented
> I think having these at runtime would be useful so users don't need to look for the correct code for the language they're using.

Yeah I was thinking exactly that. I did the same thing with an object in a gist. Could any of you explain why is not proper to use an enum for it?

2024-05-27 20:09 UTC, KnorpelSenf commented
> I think having these at runtime would be useful

So far, it's been a strict rule that this package exposes types only, and 0 bytes of executable code. We only really use `.ts` files because `.d.ts` was hard to import on Deno back then.

It's mostly for historic reasons that I'm not comfortable with this, but historic reasons are bad reasons, so please give me a few days to change my mind or to come up with a better solution :D

2024-05-27 20:17 UTC, KnorpelSenf commented
> Could any of you explain why is not proper to use an enum for it?

There are many articles on the web that explain this better than i can could in a GitHub comment. One of them is https://dev.to/ivanzm123/dont-use-enums-in-typescript-they-are-very-dangerous-57bh.

2024-05-28 16:29 UTC, KnorpelSenf commented on langs.ts
> +const LanguageCodes = {
```suggestion
export const LanguageCodes = {
```
because otherwise there's no reason to have this value at runtime at all

2024-06-02 02:22 UTC, carafelix commented
Examples of the readability benefiting from adding the Language Code runtime object. It's more clear for languages that their respective code does not resemble their name in english :
```ts
const i18n = new I18n<MyContext>({
  defaultLocale: LanguageCodes.German, // Instead of 'de'
  directory: "locales",
});
i18n.loadLocaleSync("LanguageCodes.Greek", { // Instead of 'el'
  source: `greeting = Γειά σου { $name }!
language-set = Λορεμ ιπσθμ δολορ σιτ αμετ`,
});
```
```ts
cmds.command("duke", "_", () => {})
                .localize(LanguageCodes.Croatian, "vojvoda", "_") // instead of 'hr'
```                
```ts
bot.hears('something', (ctx) => {
  ctx.api.setMyShortDescription('快乐机器人', LanguageCodes.Chinese) // instead of 'zh'
  ctx.api.setMyName('robot sásta', LanguageCodes.Irish) // instead of 'ga'
})
```

2024-06-16 12:35 UTC, KnorpelSenf approved these changes

2024-06-16 12:35 UTC, merged